sudo: required

services:
  - docker

notifications:
  email: false
  slack: ornl-cees:FX6IUxl1JcMpk2xRVJ7ygb7Y

language: python

before_install:
  - env
  - docker pull dalg24/cap-stack
  - docker run
        --detach --tty
        --name=test-machine
        --volume ${TRAVIS_BUILD_DIR}:/scratch/source/cap
        --env TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
        --env CTEST_BUILD_NAME="$(./docker/get_build_info.sh)"
        dalg24/cap-stack
  - docker ps -a
  - docker exec test-machine
        /scratch/source/cap/docker/build_cap.sh
  - docker exec test-machine
        bash -c "cd /scratch/build/cap && make coverage-cpp && make coverage-python && sed -i.fixpath 's|/dummy/cap||g' lcov.info && sed -i.fixpath 's|python/pycap|python/source|g' coverage.xml"
  - docker cp test-machine:/scratch/build/cap/lcov.info .
  - docker cp test-machine:/scratch/build/cap/coverage.xml .

install:
  - pip install -q codecov

script:
  - echo "Hello World"

after_success:
  - codecov
        --disable gcov search pycov
        --file lcov.info coverage.xml
