FROM rombur/mfmg-stack:19.07.0

ENV DEAL_II_NUM_THREADS=3

RUN git clone https://github.com/ORNL-CEES/mfmg.git && \
    cd mfmg && \
    mkdir -p build && cd build && \
    cmake \
      -D CMAKE_INSTALL_PREFIX=/opt/mfmg \
      -D CMAKE_BUILD_TYPE=Release \
      -D DEAL_II_DIR=${DEAL_II_DIR} \
      -D MFMG_ENABLE_AMGX=ON \
      -D AMGX_DIR=${AMGX_DIR} \
      -D LAPACK_DIR=${OPENBLAS_DIR} \
      .. && \
    make -j2 && make install
